version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  logstash:
    build: logstash
    networks:
      - esnet
    depends_on:
      - elasticsearch
    deploy:
      replicas: 1

volumes:
  esdata:
    driver: rexray
    driver_opts:
      size: 2

networks:
  esnet:
